### ISSUE TITLE
Remove Coolors

### ISSUE THREAD

**Issue by psjnek** [corbindavenport/shop-list#23]
The list seems to recognize [Coolors](https://coolors.co/) as a shopping website even though it is not related to shopping at all.

**Comment by psjnek** [comment]
@corbindavenport 
Hey, do you want me to remove Coolors from the list?

**Comment by corbindavenport** [comment]
No need to close the issue until it's resolved, I'm just slow to answer issues/pull requests here. I don't see `coolors.co` in the current list, maybe if it was in there it got removed at some point?

**Comment by psjnek** [comment]
> No need to close the issue until it's resolved, I'm just slow to answer issues/pull requests here. I don't see `coolors.co` in the current list, maybe if it was in there it got removed at some point?

Oh, thanks for responding. Could you also take a look at my pull request for your Wii Shop music browser extension?

**Comment by corbindavenport** [comment]
Yep, I plan on going through all the pending issues and PRs there soon while I work on the manifest V3 port :)

**Comment by psjnek** [comment]
> No need to close the issue until it's resolved, I'm just slow to answer issues/pull requests here. I don't see `coolors.co` in the current list, maybe if it was in there it got removed at some point?

I don't see "coolors.co" in the current list either. I suspected "cashconverters.co.uk" to cause the problem but that wasn't an issue.

**Comment by corbindavenport** [comment]
Ah gotcha, I'll close this issue then. Feel free to open a new one if there's a wrong site.
